export const theme = {
  colors: {
    primary: '#B8860B',      // dark goldenrod - jewellery feel
    primaryDark: '#8B6914',
    primaryLight: '#E8C547',
    background: '#FFFEF7',
    surface: '#FFFFFF',
    card: '#FFFBEB',
    text: '#1C1917',
    textSecondary: '#78716C',
    paid: '#059669',
    pending: '#DC2626',
    overdue: '#EA580C',
    border: '#E7E5E4',
    gold: '#D4AF37',
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  radius: { sm: 8, md: 12, lg: 16, xl: 20 },
  typography: {
    title: { fontSize: 22, fontWeight: '700' as const },
    titleLarge: { fontSize: 26, fontWeight: '700' as const },
    subtitle: { fontSize: 16, fontWeight: '600' as const },
    body: { fontSize: 15 },
    caption: { fontSize: 13 },
    captionSmall: { fontSize: 12 },
  },
  shadows: {
    sm: {
      shadowColor: '#1C1917',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 3,
      elevation: 2,
    },
    md: {
      shadowColor: '#1C1917',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 4,
    },
    lg: {
      shadowColor: '#1C1917',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
  },
};
